# -*- mode: python ; coding: utf-8 -*-
# Релизная сборка: без консоли, с иконкой.

HIDDEN_IMPORTS = [
    'websockets',
    'websockets.legacy',
    'websockets.legacy.server',
    'websockets.legacy.client',
    'websockets.asyncio',
    'websockets.asyncio.server',
    'websockets.asyncio.client',
    'pypresence',
    'pypresence.presence',
    'pypresence.baseclient',
    'pypresence.payloads',
    'pypresence.utils',
    'pystray',
    'pystray._win32',
    'pystray._base',
    'PIL',
    'PIL.Image',
    'PIL.ImageDraw',
    'PIL.ImageFont',
    'PIL.ImageTk',
    'PIL._tkinter_finder',
    'tkinter',
    'tkinter.messagebox',
    'tkinter.font',
    'asyncio',
    'asyncio.base_events',
    'asyncio.events',
    'asyncio.futures',
    'asyncio.tasks',
    'asyncio.streams',
    'asyncio.subprocess',
    'asyncio.windows_events',
    'asyncio.windows_utils',
    'configparser',
    'socket',
    'threading',
    'json',
    'io',
    'struct',
    'aiohttp',
    'aiohttp.web',
    'multidict',
    'yarl',
    'aiosignal',
    'frozenlist',
    'suno_stats',
]

a = Analysis(
    ['suno_rpc.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=HIDDEN_IMPORTS,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SunoRPC',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='suno_rpc.ico',
)
