# -*- mode: python ; coding: utf-8 -*-
# Debug-сборка: с консолью, чтобы видеть ошибки при запуске.

block_cipher = None

a = Analysis(
    ['suno_rpc.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'websockets',
        'websockets.legacy',
        'websockets.legacy.server',
        'websockets.legacy.client',
        'websockets.asyncio',
        'websockets.asyncio.server',
        'websockets.asyncio.client',
        'pypresence',
        'pypresence.presence',
        'pypresence.baseclient',
        'pypresence.payloads',
        'pypresence.utils',
        'pystray',
        'pystray._win32',
        'pystray._base',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'PIL.ImageTk',
        'PIL._tkinter_finder',
        'tkinter',
        'tkinter.messagebox',
        'tkinter.font',
        'asyncio',
        'asyncio.base_events',
        'asyncio.events',
        'asyncio.futures',
        'asyncio.tasks',
        'asyncio.streams',
        'asyncio.subprocess',
        'asyncio.windows_events',
        'asyncio.windows_utils',
        'configparser',
        'socket',
        'threading',
        'json',
        'io',
        'struct',
        'aiohttp',
        'aiohttp.web',
        'multidict',
        'yarl',
        'aiosignal',
        'frozenlist',
        'suno_stats',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='SunoRPC_debug',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='suno_rpc.ico',
)
